smtp.host.mail=
smtp.mail.port=
mail.user=
mail.password=
mail.noreply=
admin.password=
sql.url.local=
sql.url.test=
sql.url.dev=
sql.url.prod=
sql.user=
sql.password=
cbs.user.test=
cbs.password.test=
cbs.user.prod=
cbs.password.prod=
catalina.realm.user=
catalina.realm.password=
mail.service.formation=
mail.admin.formation=
mail.gapp=
mail.rh=
web.url.localhost=
web.url.dev=
web.url.test=
web.url.prod=
admin.url.localhost=
admin.url.dev=
admin.url.test=
admin.url.prod=
stats.url.localhost
stats.url.dev
stats.url.test
stats.url.prod
documents.url