INSERT INTO REPONSE(IDREPONSE, IDINSCRIPTION, IDQUESTION, CHOIX, SPECIFICATION, DATEREPONSE)
SELECT
  /*SEQ_REPONSE.NEXTVAL AS IDREPONSE,*/
  i.IDINSCRIPTION AS IDINSCRIPTION,
  q.IDQUESTION AS IDQUESTION,
  CASE WHEN q.SPECIFICATION = 'false' THEN q.LIBELLECHOIX1 ELSE '' END AS CHOIX,
  CASE WHEN q.SPECIFICATION = 'true' THEN '27/11/2015' ELSE '' END AS SPECIFICATION,
  TO_DATE('20160712', 'yyyymmdd') AS DATEREPONSE
FROM
  (
    SELECT *
    FROM INSCRIPTION
    WHERE IDINSCRIPTION NOT IN (
      SELECT DISTINCT(i.IDINSCRIPTION)
      FROM INSCRIPTION i, REPONSE r
      WHERE r.IDINSCRIPTION = i.IDINSCRIPTION
    )
  ) i,
  SESSIONS s,
  TYPEFORMATION t,
  QUESTION q
WHERE i.IDSESSIONS1 = s.IDSESSIONS
  AND s.IDTYPEFORMATION = t.IDTYPEFORMATION
  AND t.IDTYPEFORMATION = q.IDTYPEFORMATION;